version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: app
    restart: always
    env_file: 
      - ./env_files/.env
    volumes:
      - ./app:/app
      - ./web/static:/web/static
      - ./web/media:/web/media
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internal-network
    depends_on:
      - psql
  
  psql:
    image: postgres:15.7-bullseye
    container_name: psql
    restart: always
    env_file: 
      - ./env_files/.env
    ports:
      - 5432:5432
    networks:
      - internal-network
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
  
  client_mqtt:
    build:
      context: .
      dockerfile: client.dockerfile
    container_name: client
    restart: always
    env_file: 
      - ./env_files/.env
    networks:
      - internal-network
    depends_on:
      - psql
    volumes:
      - ./data_client:/data_client/

networks:
  internal-network:
    driver: bridge
